# fly.toml app configuration file generated for tcrb-crs-api on 2025-08-19T12:01:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tcrb-crs-api'
primary_region = 'iad'

[build]
  image = 'ghcr.io/xyphrius/tcrb-crs-api-with-connectors:latest'

[env]
  METRICS_PUBLIC = 'false'
  NODE_ENV = 'production'
  PORT = '8080'
  SENTRY_ENVIRONMENT = 'production'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80

  [services.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 100

  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
