app = "tcrb-crs-api"
primary_region = "iad"

[build]
  image = "ghcr.io/xyphrius/tcrb-crs-api-with-connectors:latest"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  METRICS_PUBLIC = "false"
  SENTRY_ENVIRONMENT = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [[services.ports]]
    port = 80

  [services.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 200

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/health"
